### ISSUE TITLE
Invalid/no generation_config.json file

### ISSUE THREAD

**Issue by ceferisbarov** [willdone1337/lm_az#1]
Inference script throws the following error:
```bash
$ python3 infer_alpaca_az.py 
../models/mGPT-1.3B-azerbaijan
/home/user/projects/lm_az/env/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:682: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
/home/user/projects/lm_az/env/lib/python3.10/site-packages/transformers/utils/hub.py:374: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/user/projects/lm_az/self_instruct/infer_alpaca_az.py", line 30, in <module>
    generation_config = GenerationConfig.from_pretrained('../models/mGPT-1.3B-azerbaijan',max_length=1024,use_auth_token=True,local_files_only=True)
  File "/home/user/projects/lm_az/env/lib/python3.10/site-packages/transformers/generation/configuration_utils.py", line 711, in from_pretrained
    resolved_config_file = cached_file(
  File "/home/user/projects/lm_az/env/lib/python3.10/site-packages/transformers/utils/hub.py", line 401, in cached_file
    raise EnvironmentError(
OSError: ../models/mGPT-1.3B-azerbaijan does not appear to have a file named generation_config.json. Checkout 'https://huggingface.co/../models/mGPT-1.3B-azerbaijan/main' for available files.
```

**Comment by pancarnas** [comment]
Thanks for the feedback. The generation config is as usual as other generation configs.  Pls save this dict as json in mGPT model dir.
{
    "_from_model_config": true,
    "bos_token_id": 1,
    "eos_token_id": 2,
    "pad_token_id": 0,
    "temperature": 0.4,
    "top_p": 0.8,
    "top_k": 40,
    "do_sample": true,
    "max_new_tokens": 1536,
    "repetition_penalty": 1.1,
    "no_repeat_ngram_size": 15,
    "transformers_version": "4.28.0.dev0"
  }
